[editor]
auto-pairs = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.lsp]
display-messages = true

[keys.normal]
"esc" = ["collapse_selection", ":w"]
